# SSH access to instances in the private subnet, tunneled over SSM Session
# Manager instead of a direct port 22 opening (see the security group's
# ingress comment in security_groups.tf). This requires the AWS CLI's
# session-manager-plugin to be installed locally.

resource "local_sensitive_file" "ssh_private_key" {
  filename        = "${path.module}/ex-broadcaster.pem"
  content         = tls_private_key.ssh.private_key_openssh
  file_permission = "0600"
}

resource "local_file" "ssh_config" {
  filename = "${path.module}/ssh_config"
  content  = <<-EOF
    # Generated by Terraform. Include this in your ~/.ssh/config with:
    #   Include ${abspath(path.module)}/ssh_config
    Host ex-broadcaster
      User ubuntu
      IdentityFile ${local_sensitive_file.ssh_private_key.filename}
      IdentitiesOnly yes
      ProxyCommand sh -c "aws ssm start-session --region ${var.aws_region} --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"
  EOF
}

output "ssh_connect_instructions" {
  description = "How to SSH into an ex_broadcaster instance via SSM Session Manager"
  value       = <<-EOF
    1. Install the Session Manager plugin for the AWS CLI, if not already installed:
       https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html
    2. Find an instance ID:
       aws ec2 describe-instances --region ${var.aws_region} --filters "Name=tag:Name,Values=ex-broadcaster" "Name=instance-state-name,Values=running" --query "Reservations[].Instances[].InstanceId" --output text
    3. Connect (replace i-xxxx with the instance ID from step 2):
       ssh -F ${local_file.ssh_config.filename} -o Hostname=i-xxxx ex-broadcaster
  EOF
}
